# version: "3"

services:
  api:
    build: ./code/deployment/api
    volumes:
      - ./models:/models
    ports:
      - "8000:8000"
    networks:
      - app-network

  app:
    build: ./code/deployment/app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
