# code/deployment/docker-compose.yml
version: "3"
services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
  app:
    build: ./app
    container_name: app
    ports:
      - "8501:8501"
    depends_on:
      - api
